version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - jac1013
  ignore:
  - dependency-name: github.com/gin-gonic/gin
    versions:
    - 1.7.0
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
  - dependency-name: github.com/sendgrid/sendgrid-go
    versions:
    - 3.7.2+incompatible
