version: '3'
services:
  api:
    build: .
    container_name: "authentication_api"
    env_file:
      - ".env"
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    command: [bash, "-c", "make build-for-docker && ./tmp/auth-server"]
